name: Close new issues with template

on:
  issues:
    types: [opened]

jobs:
    close-new-issues:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/github-script@v3
          with:
            github-token: ${{secrets.GITHUB_TOKEN}}
            script: |
              msg = `Sample message!`
              issue = await github.issues.get({
                owner: context.issue.owner,
                repo: context.issue.repo,
                issue_number: context.issue.number,
              });
              await github.issues.createComment({
                owner: context.issue.owner,
                repo: context.issue.repo,
                issue_number: context.issue.number,
                body: msg,
              });
              await github.issues.update({
                owner: context.issue.owner,
                repo: context.issue.repo,
                issue_number: context.issue.number,
                state: "closed"
              });

